site_name: AI2Business
site_url: https://ai2business.github.io/ai2business/dev
site_description: Smart solutions for Business with AI.
site_author: AI2Business & coworkers


docs_dir: sources
repo_url: https://github.com/AI2Business/ai2business
repo_name: AI2Business
edit_uri: edit/main/docs/sources

# Copyright
copyright: Copyright &copy; 2020 - AI2Business

theme:
    name: "material"
    palette:
      - scheme: dracula
        primary: indigo
        accent: blue
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
      - scheme: dracula
        primary: blue
        accent: light blue
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
    font:
        text: Roboto
        code: Roboto Mono
    icon:
        logo: material/library
        repo: material/github
    favicon: assets/favicon.png
    features:
      - navigation.tabs
      - navigation.sections
      - navigation.expand
      - search.suggest
      - search.highlight
    static_templates:
      - 404.html

markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - pymdownx.superfences:
  - pymdownx.emoji:
  - pymdownx.highlight:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: ai2business
      repo: ai2business
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline

extra_javascript:
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js

  - js/version-select.js
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/ai2business
    version:
        method: mike

plugins:
  - search
  - macros
  - mkdocstrings:
        watch:
          - ai2business
  - git-revision-date-localized

nav:
  - Home: index.md

  - Documentation:
      - Sample Generators: Sample_Generators.md
      - Trend Search: Key_Performance_Collection.md
      - AutoMLRun: AutoML_for_NeuralNetworks.md
      - Oneliner: Oneliner.md
  - Tutorials:
      - Trend Search: tutorials/trend_search_tutorial.md
      - AutoML: tutorials/timeseries_forecast_tutorial.md
  - API:
      - Key Performance Collector:
          - Finance-Collector: finance_collector_api.md
          - Trends-Collector: trends_collector_api.md
      - Datasets:
          - Sample Generator: sample_generator_api.md
      - Visualization:
          - Data Visualization: data_visualization_api.md
      - Auto Machine Learning:
          - Deep Learning: deep_learning_api.md
extra_css:
  - css/version-select.css
